# SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=wsp;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=tiger
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.security.user.name=wsong
spring.security.user.password=tiger
spring.security.user.roles=USER,ADMIN
spring.mvc.hiddenmethod.filter.enabled=true
spring.thymeleaf.check-template-location=true
spring.thymeleaf.prefix=classpath:/static/
#spring.thymeleaf.excluded-view-names= # comma-separated list of view names that should be excluded from resolution
#spring.thymeleaf.view-names= # comma-separated list of view names that can be resolved
#spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
#spring.thymeleaf.encoding=UTF-8
#spring.thymeleaf.content-type=text/html # ;charset=<encoding> is added
#spring.thymeleaf.cache=true # set to false for hot refresh
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.boot.autoconfigure.security=INFO
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG
